language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.14"
before_install:

    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
    - "git clone --branch travis_test --depth 1 https://github.com/EMBL-EBI-GCA/bp_project.git ~/bp_project"
    - "cpanm --installdeps ~/bp_project"

env:
  global:
    -PERL5LIB=$PERL5LIB:~/bp_project/lib

script:
  perl Build.PL && ./Build build

