language: perl
sudo: false
perl:
  - "5.16"
before_install:
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
    - "git clone --branch master --depth 1 https://github.com/EMBL-EBI-GCA/reseqtrack ~/reseqtrack"

env:
  global:
    -PERL5LIB=$PERL5LIB:~/reseqtrack/modules

script:
  perl Build.PL && ./Build build  && cover -test -report coveralls

