language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.14"
before_install:
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"
    - "git clone --branch master --depth 1 https://github.com/EMBL-EBI-GCA/bp_project.git ~/bp_project"
    - "git clone --branch master --depth 1 https://github.com/EMBL-EBI-GCA/reseqtrack ~/reseqtrack"
    - "cpanm --installdeps ~/bp_project"
    - "cpanm --installdeps ~/reseqtrack"

env:
  global:
    -PERL5LIB=$PERL5LIB:~/bp_project/lib
    -PERL5LIB=$PERL5LIB:~/reseqtrack/modules

script:
  perl Build.PL && ./Build build  && cover -test -report coveralls

